#! /usr/bin/env node
if (process.argv.length !== 3){
  console.log("boilerplate takes in 1 argument (file name)");
  return;
}

const readline = require("readline");
const fs = require("fs");

let htmlFileName = process.argv[2];
if (htmlFileName.slice(-5) !== ".html") {
  htmlFileName += ".html";
}

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
})

/************************/
/*       Prompts        */
/************************/
let pageTitle, cssFilePath, jsFilePath;
const prompts = [
  "Enter page title (press enter to skip):",
  "Enter path to CSS file (press enter to skip):",
  "Enter path to JS file (press enter to skip):"
];
promiseQuestion(prompts[0])
  .then(title => {
    pageTitle = title;
    return promiseQuestion(prompts[1]);
  })
  .then(cssPath => {
    return promiseCheckFile(cssPath);
  })
  .then(verifiedPath => {
    cssFilePath = verifiedPath;
    return promiseQuestion(prompts[2]);
  })
  .then(jsPath => {
    return promiseCheckFile(jsPath);
  })
  .then(verifiedPath => {
    jsFilePath = verifiedPath;
    rl.close();
    createHTML(htmlFileName, pageTitle, cssFilePath, jsFilePath);
  })
  .catch(reason => {
    console.log(reason);
  });


/************************/
/* Function definitions */
/************************/
function promiseCheckFile(path, content = "") {
  // Try to open file; create file if it doesn't exist (on error)
  return new Promise((resolve, reject) => {
    fs.open(path, "r", (err, fd) => {
      if (err) {
        const dir = path.split("/").slice(0, -1).join("/");
        fs.mkdir(dir, { recursive: true }, err => {
          if (err) reject(err);
          fs.writeFile(path, content, err => {
            if (err) reject(err);
          })
        })
      } else {
        fs.close(fd, err => {
          if (err) reject(err);
        })
      }
    })
    resolve(path)
  })
}

function promiseQuestion(question) {
  return new Promise((resolve, reject) => {
    rl.question(question + "\n", answer => {
      resolve(answer);
    })
  })
}

function createHTML(htmlFile, title, css, js) {
  const htmlString =
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="${css}" />
    <title>${title}</title>
  </head>

  <body>
    <script type="application/javascript" src="${js}"></script>
  </body>
</html>
`

  fs.writeFile(htmlFile, htmlString, err => {
    if (err) throw err;
    console.log(`Boilerplate ${htmlFile} written.`);
  })
}
